name: sip_ua
version: 0.2.1
description: A dart-lang version of the SIP UA stack.
homepage: https://github.com/cloudwebrtc/dart-sip-ua
environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0"
#  sdk: ">=2.12.0 <3.0.0"
#  flutter: ">=1.20.0"

dependencies:
  crypto: ^3.0.1
#  flutter_webrtc: ^0.2.8
  flutter_webrtc:
    git:
      url: https://github.com/vinhcuong/flutter_webrtc.git

      ref: 0.0.2
  parser_error: ^0.2.0
  sdp_transform: ^0.3.2
  uuid: ^3.0.5
  random_string: ^2.3.1
#  logger: ^1.0.0

  logger: ^0.7.0+2
  intl: ^0.17.0
  recase: ^4.0.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.6.7
